import asyncio
import uuid
from datetime import date

import httpx

from seriesdata import MorningStarSeries


class MorningstarClient:
    PUBLIC_REST_BASE_URL = "https://tools.morningstar.co.uk/api/rest.svc"
    PUBLIC_REST_API_KEY = "t92wz0sj7c"
    PRICE_CURRENCY_BY_SECURITY_ID = {
        # These UCITS ETFs expose listed market prices in USD on the legacy REST endpoint.
        "F000016OZH": "USD",
        "F000014VZD": "USD",
        "F00000XPTP": "USD",
    }

    def __init__(self, timeout_seconds: float = 30.0, retries: int = 3, base_delay: float = 1.0):
        self.client = httpx.AsyncClient(timeout=httpx.Timeout(timeout_seconds), follow_redirects=True)
        self.retries = retries
        self.base_delay = base_delay

    async def close(self):
        await self.client.aclose()

    @staticmethod
    def _is_cloudfront_error(status_code: int, response_text: str) -> bool:
        content = response_text.lower()
        return (
            status_code in (403, 429, 503)
            and ("cloudfront" in content or "request blocked" in content or "generated by cloudfront" in content)
        )

    async def _get_with_retry(
        self,
        url: str,
        headers: dict[str, str],
        params: dict[str, str] | None = None,
    ) -> httpx.Response | None:
        for attempt in range(self.retries + 1):
            try:
                response = await self.client.get(url, headers=headers, params=params)
                if self._is_cloudfront_error(response.status_code, response.text):
                    print(f"CloudFront blocked request (attempt {attempt + 1}/{self.retries + 1}) for URL: {url}")
                    if attempt < self.retries:
                        await asyncio.sleep(self.base_delay * (attempt + 1))
                        continue
                return response
            except (httpx.ConnectTimeout, httpx.ReadTimeout, httpx.WriteTimeout, httpx.PoolTimeout) as ex:
                print(f"Timeout fetching {url} (attempt {attempt + 1}/{self.retries + 1}): {ex}")
                if attempt < self.retries:
                    await asyncio.sleep(self.base_delay * (attempt + 1))
                    continue
                return None
            except httpx.RequestError as ex:
                print(f"Request error fetching {url}: {ex}")
                return None
        return None

    async def collect_maas_token(self, ticker_query: str = "0P0001I3S0") -> str:
        url = f"https://global.morningstar.com/en-gb/investments/etfs/{ticker_query}/chart"
        headers = {
            "Accept": "application/json",
            "Accept-Language": "en-GB,en;q=0.9",
            "Cache-Control": "no-cache",
            "Pragma": "no-cache",
            "Origin": "https://global.morningstar.com",
            "Referer": f"https://global.morningstar.com/en-gb/investments/etfs/{ticker_query}/chart",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 OPR/122.0.0.0",
            "x-api-requestid": str(uuid.uuid4()),
        }

        response = await self._get_with_retry(url, headers)
        if response is None:
            raise Exception("Failed to fetch Morningstar page after retries")
        if self._is_cloudfront_error(response.status_code, response.text):
            raise Exception("Morningstar returned a CloudFront block page while collecting maasToken")

        html = str(response.text)
        if 'maasToken:"' in html:
            try:
                return html.split('maasToken:"')[1].split('"')[0]
            except Exception as ex:
                raise Exception("maasToken was not found in the response") from ex

        raise Exception("Failed to fetch data")

    @classmethod
    def _get_price_currency_id(cls, security_id: str) -> str:
        return cls.PRICE_CURRENCY_BY_SECURITY_ID.get(security_id, "EUR")

    @staticmethod
    def _build_public_security_query_id(security_id: str) -> str:
        return f"{security_id}]2]0]FOEUR$$ALL"

    async def _fetch_public_timeseries(
        self,
        security_id: str,
        start_date: date,
        end_date: date,
        price_type: str,
    ) -> dict[date, float]:
        url = f"{self.PUBLIC_REST_BASE_URL}/timeseries_price/{self.PUBLIC_REST_API_KEY}"
        headers = {
            "Accept": "application/json",
            "Referer": "https://tools.morningstar.co.uk/",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
        }
        params = {
            "currencyId": self._get_price_currency_id(security_id),
            "idtype": "Morningstar",
            "frequency": "daily",
            "outputType": "JSON",
            "priceType": price_type,
            "startDate": start_date.isoformat(),
            "endDate": end_date.isoformat(),
            "id": self._build_public_security_query_id(security_id),
        }

        response = await self._get_with_retry(url, headers=headers, params=params)
        if response is None:
            print(f"Failed to fetch {price_type} history for {security_id}: request failed after retries")
            return {}

        if response.status_code != 200:
            print(f"Failed to fetch {price_type} history for {security_id}: HTTP {response.status_code}")
            return {}

        try:
            payload = response.json()
            history_items = payload["TimeSeries"]["Security"][0]["HistoryDetail"]
        except (ValueError, KeyError, IndexError, TypeError) as ex:
            print(f"Failed to parse {price_type} history for {security_id}: {ex}")
            return {}

        parsed_history: dict[date, float] = {}
        for item in history_items:
            raw_date = item.get("EndDate")
            raw_value = item.get("Value")
            if not raw_date or raw_value in (None, ""):
                continue

            try:
                parsed_history[date.fromisoformat(raw_date)] = float(raw_value)
            except (TypeError, ValueError):
                continue

        return parsed_history

    async def fetch_history(
        self,
        ticker_query: str,
        start_date: date,
        end_date: date = date.today(),
    ) -> list[MorningStarSeries]:
        price_history, nav_history = await asyncio.gather(
            self._fetch_public_timeseries(
                ticker_query,
                start_date=start_date,
                end_date=end_date,
                price_type="PRICE",
            ),
            self._fetch_public_timeseries(
                ticker_query,
                start_date=start_date,
                end_date=end_date,
                price_type="NAV",
            ),
        )

        if not price_history and not nav_history:
            return []

        series: list[MorningStarSeries] = []
        for history_date in sorted(set(price_history) | set(nav_history)):
            close_value = price_history.get(history_date)
            nav_value = nav_history.get(history_date)

            # The legacy public endpoint exposes close-like PRICE and NAV, but not OHLCV.
            series.append(
                MorningStarSeries(
                    date=history_date,
                    close=close_value,
                    nav=nav_value,
                )
            )

        return series
