import asyncio
import uuid
from datetime import date

import httpx

from seriesdata import MorningStarSeries


class MorningstarClient:
    def __init__(self, timeout_seconds: float = 30.0, retries: int = 3, base_delay: float = 1.0):
        self.client = httpx.AsyncClient(timeout=httpx.Timeout(timeout_seconds), follow_redirects=True)
        self.retries = retries
        self.base_delay = base_delay

    async def close(self):
        await self.client.aclose()

    @staticmethod
    def _is_cloudfront_error(status_code: int, response_text: str) -> bool:
        content = response_text.lower()
        return (
            status_code in (403, 429, 503)
            and ("cloudfront" in content or "request blocked" in content or "generated by cloudfront" in content)
        )

    async def _get_with_retry(self, url: str, headers: dict[str, str]) -> httpx.Response | None:
        for attempt in range(self.retries + 1):
            try:
                response = await self.client.get(url, headers=headers)
                if self._is_cloudfront_error(response.status_code, response.text):
                    print(f"CloudFront blocked request (attempt {attempt + 1}/{self.retries + 1}) for URL: {url}")
                    if attempt < self.retries:
                        await asyncio.sleep(self.base_delay * (attempt + 1))
                        continue
                return response
            except (httpx.ConnectTimeout, httpx.ReadTimeout, httpx.WriteTimeout, httpx.PoolTimeout) as ex:
                print(f"Timeout fetching {url} (attempt {attempt + 1}/{self.retries + 1}): {ex}")
                if attempt < self.retries:
                    await asyncio.sleep(self.base_delay * (attempt + 1))
                    continue
                return None
            except httpx.RequestError as ex:
                print(f"Request error fetching {url}: {ex}")
                return None
        return None

    async def collect_maas_token(self, ticker_query: str = "0P0001I3S0") -> str:
        url = f"https://global.morningstar.com/en-gb/investments/etfs/{ticker_query}/chart"
        headers = {
            "Accept": "application/json",
            "Accept-Language": "en-GB,en;q=0.9",
            "Cache-Control": "no-cache",
            "Pragma": "no-cache",
            "Origin": "https://global.morningstar.com",
            "Referer": f"https://global.morningstar.com/en-gb/investments/etfs/{ticker_query}/chart",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 OPR/122.0.0.0",
            "x-api-requestid": str(uuid.uuid4()),
        }

        response = await self._get_with_retry(url, headers)
        if response is None:
            raise Exception("Failed to fetch Morningstar page after retries")
        if self._is_cloudfront_error(response.status_code, response.text):
            raise Exception("Morningstar returned a CloudFront block page while collecting maasToken")

        html = str(response.text)
        if 'maasToken:"' in html:
            try:
                return html.split('maasToken:"')[1].split('"')[0]
            except Exception as ex:
                raise Exception("maasToken was not found in the response") from ex

        raise Exception("Failed to fetch data")

    async def fetch_history(
        self,
        ticker_query: str,
        maas_bearer_token: str,
        start_date: date,
        end_date: date = date.today(),
    ) -> list[MorningStarSeries]:
        url = f"https://www.us-api.morningstar.com/QS-markets/chartservice/v2/timeseries?query={ticker_query}:totalReturn,nav,open,high,low,close,volume,previousClose"
        url += "&frequency=d"
        url += f"&startDate={start_date}&endDate={end_date}"
        url += "&trackMarketData=3.6.5&instid=DOTCOM"

        headers = {
            "Accept": "application/json",
            "Accept-Language": "en-GB,en;q=0.9",
            "Cache-Control": "no-cache",
            "Pragma": "no-cache",
            "Origin": "https://global.morningstar.com",
            "Referer": "https://global.morningstar.com/",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 OPR/122.0.0.0",
            "Authorization": f"Bearer {maas_bearer_token}",
        }

        response = await self._get_with_retry(url, headers)
        if response is None:
            print(f"Failed to fetch history for {ticker_query}: request failed after retries")
            return []

        if self._is_cloudfront_error(response.status_code, response.text):
            print(f"CloudFront blocked history request for {ticker_query}")
            return []

        if response.status_code == 200:
            series = [MorningStarSeries(**item) for item in response.json()[0]["series"]]
            return sorted(series, key=lambda item: item.date)

        return []
